version: 1
formatters:
  simple:
    format: '%(asctime)s  %(name)s  %(levelname)s  %(module)s->%(funcName)s->line:%(lineno)d message : %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  console_err:
    class: logging.StreamHandler
    level: ERROR
    formatter: simple
    stream: ext://sys.stderr
  all_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: ../logs/debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 50 #保留50个log文件
        encoding: utf8
  server_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO # 只在文件中记录INFO级别及以上的log
        formatter: simple
        filename: ../logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
  debugFile:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: ../logs/all.log
    maxBytes: 10485760
    backupCount: 3
    encoding: utf8
  errorFile:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: ../logs/error.log
    maxBytes: 10485760
    backupCount: 3
    encoding: utf8
loggers:
  simpleExample:
    level: DEBUG
    handlers: [console, debugFile, server_file_handler, all_file_handler, errorFile]
    propagate: yes
root:
  level: DEBUG
  handlers: [console_err]